steps:
  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Frontend
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/pixelistic_fe:$SHORT_SHA'
    - 'pixelistic_fe'
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Backend
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/pixelistic_be:$SHORT_SHA'
    - 'pixelistic_be'
  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Frontend
    args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/pixelistic_fe:$SHORT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Backend
    args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/pixelistic_be:$SHORT_SHA'
   # This step generates the new manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Generate manifest
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      sed -i "s|__REP_WEB_URI__|gcr.io/$PROJECT_ID/pixelistic_fe:$SHORT_SHA|" pixelistic_fe/manifests/deployment.yml && \
      sed -i "s|__REACT_APP_API_WEB__|$REACT_APP_API_WEB|" pixelistic_fe/manifests/deployment.yml && \
      sed -i "s|__REACT_APP_AWS_S3__|$REACT_APP_AWS_S3|" pixelistic_fe/manifests/deployment.yml && \
      cat pixelistic_fe/manifests/deployment.yml 
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
    - 'apply'
    - '-f'
    - 'pixelistic_fe/manifests/deployment.yml'
    - '-f'
    - 'pixelistic_fe/manifests/service.yml'

    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=yg-pix-stage-gke'  