version: '3.7'

services:
    web:
        build:
            context: ./pixelistic_fe
            dockerfile: Dockerfile
            args:
              - REACT_APP_API_WEB=${API_WEB}
              - REACT_APP_AWS_S3=${AWS_S3}
        init: true
        environment:
            - NODE_ENV=development
        ports:
            - "80:80"
        restart: always    
        depends_on:
            - api
        networks:
            - frontend
    api:
        build:
            context: ./pixelistic_be
            dockerfile: Dockerfile
        init: true
        environment:
          - AWS_S3_BUCKET=${AWS_S3_BUCKET}
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_REGION=${AWS_REGION}
          - MONGO_DB=${MONGO_DB}
          - EMAIL_USER=${EMAIL_USER}
          - EMAIL_PASS=${EMAIL_PASS}
          - FRONT_URL=${FRONT_URL}
        ports:
            - "3000:3000"
        restart: always
        depends_on:
            - mongo_db
        entrypoint: ["./wait-for-it.sh", "mongo_db:27017","-t", "15", "--","node", "./bin/www"]
        networks:
            - frontend
            - backend
    mongo_db:
        image: mongo:4
        init: true
        ports:
            - "27017"
        restart: always    
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            - mongo-data:/data/db:cached
        environment:
            - MONGO_INITDB_DATABASE=${DB_NAME}
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - backend
networks:
    frontend:
    backend:
volumes:
    mongo-data:


