version: '3.7'

services:
    web:
        build:
            context: ./pixelistic_fe
            dockerfile: Dockerfile
        init: true
        environment:
            - NODE_ENV=prod
        #command: ng serve --host 0.0.0.0
        ports:
            - 80:80
        depends_on:
            - api
        networks:
            - frontend
    api:
        build:
            context: ./pixelistic_be
            dockerfile: Dockerfile
        init: true
        ports:
            - 3000:3000
        depends_on:
            - mongo_db
        environment:
          - MongoSettings__ConnectionString=mongodb://mongo_db:27017
          - mongoose__connect=mongodb://admin:PassMongo@mongo_db:27017/pixelapp
          - MongoSettings__DatabaseName=BookCrossingDB
        networks:
            - frontend
            - backend
    mongo_db:
        image: mongo:4
        init: true
        ports:
            - '27017-27019:27017-27019'
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - mongo-data:/data/db:cached
        environment:
            - MONGO_INITDB_DATABASE=pixelapp
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=PassMongo
        networks:
            - backend
networks:
    frontend:
    backend:
volumes:
    mongo-data:


