---
- hosts: pixelistic
  roles:
    - { role: mongodb_repository, mongodb_version: "4.0" }
    - mongodb_install
    - mongodb_selinux
    - { role: mongodb_config, config_port: 27017 }
    - { role: geerlingguy.nodejs, nodejs_version: "10.x" }
    - deploy

  vars:
    - skeleton_port: 80
