apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatalyakpixelisticbe
  labels:
    app: gatalyakpixelisticbe  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelisticbe  
  template:
    metadata:
      labels:
        app: pixelisticbe 
    spec:
      containers:
        - name: pixelisticbe 
          image: __REP_API_URI__:latest
          ports:
          - containerPort: 3000
          env:
          - name: MONGO_DB
            value: __MONGO_DB__
          - name: FRONT_URL
            value: __FRONT_URL__
          - name: AWS_ACCESS_KEY_ID
            value: __AWS_ACCESS_KEY_ID__
          - name: AWS_SECRET_ACCESS_KEY
            value: __AWS_SECRET_ACCESS_KEY__
          - name: AWS_REGION
            value: __AWS_REGION__
          - name: AWS_S3_BUCKET
            value: __AWS_S3_BUCKET__
          - name: EMAIL_USER
            value: __EMAIL_USER__
          - name: EMAIL_PASS
            value: __EMAIL_PASS__
