- name: Open firewall ports
  firewalld:
    port: "80/tcp"
    immediate: yes
    permanent: true
    state: enabled
- name: Recursively remove app directory
  file:
    path: /opt/app
    state: absent
- name: Create app directory
  file: path=/opt/app state=directory
- name: Copy app files with owner and permissions
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{item.mode}}"
    with_items:
      - { src: './../pixelistic_fe/build',dest: '/opt/app/pixelistic_fe', mode: '0774'}
      - { src: './../pixelistic_be',dest: '/opt/app', mode: '0774'}
   



