- name: Open firewall ports
  firewalld:
    port: "80/tcp"
    immediate: yes
    permanent: true
    state: enabled
    
- name: Recursively remove app directory
  file:
    path: /opt/app
    state: absent
    
- name: Create app directory
  file: path=/opt/app state=directory
  
- name: Copy app files with owner and permissions
  copy:
    src: ./../pixelistic_fe/build
    dest: /opt/app/pixelistic_fe
    
- name: tar
  local_action: command tar zcvf ./../pixelistic_be.tgz ./../pixelistic_be
  
- name: Copy app files with owner and permissions
  copy:
    src: ./../pixelistic_be.tgz
    dest: /opt/app/
    
- name: untar
  command: tar -C /opt/app -xvzf /opt/app/pixelistic_be.tgz
  
- name: "Install forever (to run Node.js app)."
  npm: name=forever global=yes state=present

- name: Stop app process
  shell: pkill -9 node
  
  - name: Start application
  command: forever start /opt/app/pixelistic_be/bin/www
  environment:
    NODE_ENV: production  # Use this if you want to deploy the app in production
    FRONT_URL: "{{ FRONT_URL }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    MONGO_DB: "{{ MONGO_DB }}"
    EMAIL_USER: "{{ EMAIL_USER }}"
    EMAIL_PASS: "{{ EMAIL_PASS }}"
 



